image:
  - Visual Studio 2019

pull_requests:
  do_not_increment_build_number: true

skip_branch_with_pr: true

branches:
  only:
    - main
    - develop
    - /release\/.*/
    - /hotfix\/.*/

# no test, no auto-build - everything is cake (see build_script)
test: off
build: off

build_script:
  - ps: .\build.ps1 --target=CI --verbosity=Diagnostic

cache:
  - "tools -> recipe.cake"
